### ISSUE TITLE
RFF, Download + ls

### ISSUE THREAD

**Issue by andresmijares** [decentraland/ipfs-node#13]
## Context
Can we add a ls command?
Download should not return a json, it should return the file or encode the response in bas64 or similar

@eordano 
What would be different between a `ls` vs current `dependencies/ipfs` (in branch `development`)??

## Features
- endpoint for download
- endpoint for ls TBD

**Comment by eordano** [comment]
`ls` would be listing all the IPFS hashes under a folder
`dependencies` is specific to our `scene.json` file, right?

**Comment by andresmijares** [comment]
actually it does not, if there is a `scene` folder, it would list the direct children's IPFS hashes @eordano

**Comment by andresmijares** [comment]
Download is a tricky case, the current implementation won't fit the use case, we need to figure it out a way to support multiples cases, for example, since this is a `cat` operations, we can do something like (low level implementation)

`ipfs cat ipfs/{hash} > somefilename.txt`

We can place that file into a folder and send that new file to the user.

This would work for txt related files, but not for other kind.

I'm open to suggestion about how to handle this problem. Also having check a look at [ipget](https://github.com/ipfs/ipget) this might seem a good use case to replace this node in the future.
