### ISSUE TITLE
Decentraland IPFS BlackList

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/ipfs-node#14]
## Motivation

As the urge to prevent Decentraland to serve illegal content, we decided to create an IPFS hash blacklist

``` 
# decentraland-blacklist.txt
ipfs_1
ipfs_2
ipfs_3
.
.
.
ipfs_N 
```

#### NEW

| Endpoint| Method | Response |
| ------------- |:-------------:|-------------|
| api/blacklist/:ipfsHashes| GET | { data: object, url: { ipns: string } |
| api/blacklist/:ipfsHashes | POST | { url: { ipns: string } | 

@GET /blacklist

- Return an object key -> value where the key is the ipfs_hash and the value is a boolean referencing if it is allowed or not. We are going to cache the request/response

##### ❗️ Important

If the endpoint is called from a Non-Decentraland app and the request is not cached we will return data as `null` and the `IPNS` where the user can check by its own node if the IPFS hashes are allowed

```
# @GET
# api/blacklist/:ipfsHashes
# If request is from Decentraland App or is cached should return
{
  "ok": true,
  "data": {
    "ipfs_1": true,
    "ipfs_2" true,
    "ipfs_3" false
  },
  "url": {
    "ipns": "ipns_hash"
  }
}

# If request is not cached and comes from Non-Decentraland app
{
  "ok": true,
  "data": null,
  "url": {
    "ipns": "ipns_hash"
  }
}
```

@POST /blacklist/:ipfsHashes

* Check if sender is allowed to perform this action
* Get current blacklist
* Append new hashes
* Publish updated file

```
# @POST
# api/blacklist
# Payload
{ 		
    "ipfs": [ipfs_1, ipfs_2, ipfs_3, … , ipfs_n]
}
# Should return:
{
  "ok":true,
  "url": {
    "ipns": IPNS_HASH
  }
}
```

Decentraland’s apps, as [LENS](https://github.com/decentraland/lens), are going to be the allowed ones to update the blacklist, therefore, we should need to use a cryptographic infrastructure, IP check or whatever, to ensure 100% it.

#### UPDATE

All existing endpoints must check before action if the IPFS hash to handle an operation it is blacklisted or not

#### NICE TO HAVE
Also, as we can’t ensure the illegal content addresses by IPFS hashes won’t be served because some users could get them direct by our IPFS node instead of the interface, we could run a script which goes through the blacklist and removes refs from Decentraland’s IPFS node/s

### NOTES

We could use `/blacklist` as a path in case we want to address more files under the node peerID (IPNS)

### WHERE STORE IPFS HASHES

| |CONS | PRO |
| ------------- |:-------------|:-------------|
| DB| - Have one table with one column seems overly<br>- Get all the records in order to generate a file to be uploaded/updated to IPFS| - Can be accessed from other Decentraland Apps with DB conection<br>- Time complexity for operating over a table with 100M.K records table?<br>
| .txt | - Precarious<br>- Not a solution if we will use more than one IPFS node<br>- Can not be directly accessed from others Decentraland Apps | - Grep operations are fast<br>- Time complexity for operate in a 100M.K records file?<br>- As we already have the file we can upload/update it to IPFS with one operation | 

### Implementation

Run a process (CRON) every 3-4 hours which gets declined IPFS hashes, create a `.txt` file and upload it to an S3 bucket. 

This file will has read access for everyone.

#### NEW

| Endpoint| Method | Response |
| ------------- |:-------------:|-------------|
| api/blacklist/:ipfsHashes| GET | { data: object } |

@GET /blacklist

- Return an object key -> value where the key is the ipfs_hash and the value is a boolean referencing if it is allowed or not. We could cache the request/response

##### ❗️ Important

The endpoint will be called only by Decentraland's apps

```
# @GET
# api/blacklist/:ipfsHashes
# If request is from Decentraland App or is cached should return
{
  "ok": true,
  "data": {
    "ipfs_1": true,
    "ipfs_2" true,
    "ipfs_3" false
  }
}
```

#### NICE TO HAVE
Also, as we can’t ensure the illegal content addresses by IPFS hashes won’t be served because some users could get them direct by our IPFS node instead of the interface, we could run a script which gets the blacklist from URL and removes refs from Decentraland’s IPFS node/s

### Considerations

I'm 99% sure, delete a blacklisted hash operation will happen only under two flows: 

1 - Operator mark content as illegal by error.
2 - Under dispute, a user complains about the decision.

@eordano Those two flows are going to happen with frequency?

**Comment by nachomazzara** [comment]
> needed

**Comment by andresmijares** [comment]
I will add a piece for you to think about, since a txt file will need to be read and parsed, what about this:

1) We use a `.txt` as backup.
2) We keep a realtime column database for everyone to be able to listen for changes, we use a long polling approach to avoid stress.
3) We make sure that both, the db and txt file are in sync a few times a day.

This will avoid services to come a check a list, instead they will be listening for changes and sanity check for validation / changes (in realtime).

Notice, I'm not asking to remove the API you are proposing, I want to keep it, I'm proposing to use as source of truth a real time db which is compare and update a txt file on regular basis.

**Comment by nachomazzara** [comment]
> I will add a piece for you to think about, since a txt file will need to be read and parsed, what about this:
> 
> We use a .txt as backup.

👍 Yes, totally agree! we should have a `.txt` file as backup and also we could use it to provide an updated state of hashes to our apps if the update into IPFS take some time to refresh

> We keep a realtime column database for everyone to be able to listen for changes, we use a long polling approach to avoid stress.
> We make sure that both, the db and txt file are in sync a few times a day.
> This will avoid services to come a check a list, instead they will be listening for changes and sanity check for validation / changes (in realtime).

Let me check If I got the point. 

You are proposing to use a Table to save what we are going to have in the `.txt` as a way to create a listener with polling approach for our apps, right?

In this case, as *LENS* is the only app we have right now that will publish IPFS state to the blacklist, I don't see a really good use case to do it. All the content we want to show at Decentraland is on-demand so, why it is useful to have a blacklist listener provided by the IPFS-node? 

In my opinion, this feature would be useful when we have more than one app updating the blacklist

Am I not seeing something you have in mind?

**Comment by andresmijares** [comment]
`As a consumer, I want to be able to request to remove multiple elements for a blacklist and displayed back in the world in the short period of time`.

Your implementation might be ok for pushing changes to a list, I meaning for listening changes instead.

We are not checking content before being published, we follow a upload first, check later approach, having said this, multiples sources needs will to sanitize if a content is proper, when the application get into a bigger state multiples services will need to consume this data and being able to react to changes as soon as possible.

All good about add elements to BL, what about removing? what about removing objects in the middle? what about bulking updates to take out a BL?  do we have to iterate one by one? this is part what I dont' feel comfortable a about a .txt list, they have to be inmutable (again, for an mvp is ok, for a production at scale system, I kindly disagree) these are array of data, what is the more fucked up operation in an array of data? removing elements in the middle (that's what I mean this is a blocking operation).

Always tell, don't ask for reference.

I'm concern about the fact that updating a list is a blocking and relative expensive operation, there are several pattern to solve this problem, isolating this data structure into db is one of them.

I might be seeing overthinking but architecting system is always about thinking what is going to bring problems later, not now.

**Comment by nachomazzara** [comment]
Good approach @andresmijares 

I updated the issue with a table with PROS and CONS at the end to define what is better.

As always, I prefer to use a database to save things, but in this case, I doubt a little about what is going to be _the final product_, I mean, have a file with blacklisted hash in IPFS where Non-Decentraland app could consume it. 

We can discuss it, I'm not fully convinced. Just trying to think and cover the most cases as possible.

> We are not checking content before being published, we follow an upload first, check later approach, having said this, multiples sources needs will sanitize if a content is proper, when the application gets into a bigger state multiples services will need to consume this data and being able to react to changes as soon as possible.

You are right! I redefined the @GET endpoint which checks if the IPFS hashes are allowed or not. For Decentraland app we are going to have one source of truth to know it. Are you ok with it?

> [...] I mean for listening changes instead.

Do you have an example in mind of why this is something we want? or is it something for tomorrow?

**Comment by nachomazzara** [comment]
Moved to [lens](https://github.com/decentraland/lens/pull/43)
