### ISSUE TITLE
If a parcel has no linked IPNS, it fails with 500

### ISSUE THREAD

**Issue by menduz** [decentraland/ipfs-node#17]
The response code 500 is for internal server errors. 

In our case, we might do
- Return a 404, because we cannot found the desired resource
- Return 200, with an error message in the JSON

I suggest doing the first one since we can gracefully continue our workflow without creating an exception in the client and parsing the JSON directly.

**Comment by nachomazzara** [comment]
@menduz we are returning a [403 forbidden](https://github.com/decentraland/ipfs-node/pull/16/files#diff-a7837ba49716988101af3cf502749040R31) when the parcel has not IPNS associated & when we can not connect to the peer.

Are you still seeing status 500?

**Comment by menduz** [comment]
Yep,

```http
GET /api/resolve/-2/-2
Host: ipfs.decentraland.zone
Referer: https://client.decentraland.today/
origin: https://client.decentraland.today
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

```http
HTTP/1.1 500 Internal Server Error
Date: Thu, 22 Mar 2018 13:28:49 GMT
content-type: application/json; charset=utf-8
content-length: 44
x-powered-by: Express
access-control-allow-origin: *
etag: W/"2c-stx9uWJIikzEewndeg392LCnq50"

{"error":"The land has not IPNS associated"}
```

**Comment by nachomazzara** [comment]
Oh, I see, `403` it happened only at `pin`. @menduz  It is ready in the `resolve` method too!

EDIT: Moved to `404, IPNS not found`
